### ISSUE TITLE
--param force-lavd-decoder no longer valid

### ISSUE THREAD

**Issue by MartinPulec** [CESNET/UltraGrid#237]
### Discussed in https://github.com/CESNET/UltraGrid/discussions/236

<div type='discussions-op-text'>

<sup>Originally posted by **alatteri** July 17, 2022</sup>
force-lavd-decoder no longer seems to be a valid parameter.  I am unsure how I am supposed to force decoding offload to an Nvidia card (hevc_cuvid).  

I don't see an alternative to enabling this.

```
[2022-07-16 19:57:56] Unknown parameter: force-lavd-decoder
[2022-07-16 19:57:56] Type 'uv --param help' for list.
[2022-07-16 19:57:56] common_preinit() failed!
```
</div>

**Comment by MartinPulec** [comment]
Thanks @alatteri for reporting -- yes, I've made some modifications in the early initialization code and this is perhaps a regression, most likely no `--param` actually works.

**Comment by MartinPulec** [comment]
This should be fixed now. It was a regression, indeed. (It is a bit egg-chicken problem.)

**Comment by alatteri** [comment]
I'm still getting this.

[2022-07-18 09:07:00] UltraGrid 1.7+ (master rev e561e45 built Jul 18 2022 09:03:48)
[2022-07-18 09:07:00] 
[2022-07-18 09:07:00] Unknown parameter: alsa-playback-buffer=72000
[2022-07-18 09:07:00] Type 'uv --param help' for list.

**Comment by alatteri** [comment]
and this

[2022-07-18 09:15:29] UltraGrid 1.7+ (master rev e561e45 built Jul 18 2022 09:03:48)
[2022-07-18 09:15:29] 
[2022-07-18 09:15:29] Unknown parameter: audio-buffer-len=1000
[2022-07-18 09:15:29] Type 'uv --param help' for list.

**Comment by alatteri** [comment]
and this

[2022-07-18 09:35:29] UltraGrid 1.7+ (master rev e561e45 built Jul 18 2022 09:03:48)
[2022-07-18 09:35:29] 
[2022-07-18 09:35:29] Unknown parameter: force-lavd-decoder=hevc_cuvid
[2022-07-18 09:35:29] Type 'uv --param help' for list.

**Comment by alatteri** [comment]
I concur.  This looks fixed now.  Thank you.
