### ISSUE TITLE
R12L being downconverter to 8bit for ProRes Video Toolbox

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#479]
macOS App Image

I couldn't copy/paste the log, so hence the screen shot.

<img width="575" height="161" alt="Image" src="https://github.com/user-attachments/assets/9ab9740a-fa1d-46bc-ae96-9b1aa3088819" />

**Comment by MartinPulec** [comment]
I've pushed the code with R12L conversion to ayuv64le.

Unfortunately, as I already mentioned, I couldn't have tested the conversion **prores_videotoolbox** directly. Also, no other lavc codec supports that pixel format, so I didn't manage to test it at all. Writing an unit test will be possible but it might take more time that the actual conversion (which is just adapted version of the other one).

**Comment by alatteri** [comment]
Looks like the decoder part still is not working properly.

```
MacOS % ./uv -d vulkan
MasterPortDestroyer is armed
UltraGrid 1.10+ (master rev 7cc5726 built Nov 14 2025 15:48:25)

Display device   : vulkan
Capture device   : none
Audio capture    : none
Audio playback   : none
MTU              : 9000 B
Video compression: none
Audio codec      : PCM
Network protocol : UltraGrid RTP
Audio FEC        : none
Video FEC        : none

[Vulkan SDL3] Using driver: cocoa
SDL3 initialized successfully.
[Vulkan SDL3] Path to shaders: /Applications/uv-qt.app/Contents/share/ultragrid/vulkan_shaders
[vulkan] VK_KHR_portability_enumeration required but not found... erasing this extension...
[vulkan] yCbCr feature supported.
[vulkan] Vulkan uses GPU called: Apple M2 Pro
[vulkan] Used Vulkan API: 1.1
[vulkan] Recreating swapchain, size: 1920x1080, format A2B10G10R10UnormPack32
[Vulkan SDL3] Vulkan display initialised.
[vulkan] Recreating render_pipeline
[vulkan] The GPU does not support linear filter with a YCbCr conversion sampler. Will attempt to fall back to shader conversion.
[Vulkan SDL3] Supported codecs are: RGBA UYVY VUYA Y416 R10k 
Control socket listening on port 53074
[Pbuf] [video] 128/128 packets received (100.0000%), 0 lost, max loss 0
[video dec.] New incoming video format detected: 2048x1080 @24.00p, codec PRORES_4444
Unable to find decoder for input codec "PRORES_4444"!!!
Compression internal codec is "(undefined)". Native codecs are: RGBA, UYVY, VUYA, Y416 and R10k
Could not find neither line conversion nor decompress from PRORES_4444 to display supported formats (RGBA, UYVY, VUYA, Y416 and R10k).
[video dec.] Reconfiguration failed!!!
[Vulkan SDL3] 0 frames in 5.07287 seconds = 0 FPS
[Vulkan SDL3] 0 frames in 5.02397 seconds = 0 FPS
[Vulkan SDL3] 0 frames in 5.01635 seconds = 0 FPS
[Vulkan SDL3] 0 frames in 5.01776 seconds = 0 FPS
[Vulkan SDL3] 0 frames in 5.01348 seconds = 0 FPS
[Vulkan SDL3] 0 frames in 5.01755 seconds = 0 FPS
Video dec stats (cumulative): 0 total / 0 disp / 0 drop / 0 corr / 0 miss
Pbuf: total 53993216/53993216 packets received (100.00000%).
[Vulkan SDL3] 0 frames in 5.01095 seconds = 0 FPS
[Vulkan SDL3] 0 frames in 5.01815 seconds = 0 FPS
Exit
MasterPortDestroyer triggered
```



encoder

<img width="1001" height="652" alt="Image" src="https://github.com/user-attachments/assets/b07927bf-29ba-4274-a9f9-bde2762dc418" />

**Comment by alatteri** [comment]
OK...tried with the latest Continuous 9832f9d, and the result is the same.

```
[video dec.] New incoming video format detected: 3840x2160 @24.00p, codec PRORES_4444
Unable to find decoder for input codec "PRORES_4444"!!!
Compression internal codec is "(undefined)". Native codecs are: RGBA, UYVY, VUYA, Y416 and R10k
Could not find neither line conversion nor decompress from PRORES_4444 to display supported formats (RGBA, UYVY, VUYA, Y416 and R10k).
[video dec.] Reconfiguration failed!!!
```

**Comment by MartinPulec** [comment]
The actual ProRes decode failure should be fixed now.

**Comment by alatteri** [comment]
Sorry, I think this is still not working properly.   
It is still setting pixfrmt to bgra

<img width="870" height="600" alt="Image" src="https://github.com/user-attachments/assets/a4f7fd0e-aa30-4fa9-b0ad-742834ca9f05" />
<img width="958" height="481" alt="Image" src="https://github.com/user-attachments/assets/4cf2a159-5848-4a6d-b86a-c42400a7873a" />
